AWSTemplateFormatVersion: '2010-09-09'
Description: 'WAF WebACL for CloudFront - Must be deployed in us-east-1'

Parameters:
  EnvironmentName:
    Type: String
    Default: spree-production
    Description: Environment name prefix

Resources:
  # ==================== WAF (Web Application Firewall) ====================
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub ${EnvironmentName}-waf
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      Description: WAF rules for Spree Commerce CloudFront distribution
      Rules:
        # AWS Managed Rule - Core Rule Set (CRS) with admin path exclusion
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 1
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
              ScopeDownStatement:
                NotStatement:
                  Statement:
                    ByteMatchStatement:
                      SearchString: /admin
                      FieldToMatch:
                        UriPath: {}
                      TextTransformations:
                        - Priority: 0
                          Type: NONE
                      PositionalConstraint: STARTS_WITH
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric

        # AWS Managed Rule - Known Bad Inputs with admin path exclusion
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules: []
              ScopeDownStatement:
                NotStatement:
                  Statement:
                    ByteMatchStatement:
                      SearchString: /admin
                      FieldToMatch:
                        UriPath: {}
                      TextTransformations:
                        - Priority: 0
                          Type: NONE
                      PositionalConstraint: STARTS_WITH
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric

        # AWS Managed Rule - SQL Injection with admin path exclusion
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
              ExcludedRules: []
              ScopeDownStatement:
                NotStatement:
                  Statement:
                    ByteMatchStatement:
                      SearchString: /admin
                      FieldToMatch:
                        UriPath: {}
                      TextTransformations:
                        - Priority: 0
                          Type: NONE
                      PositionalConstraint: STARTS_WITH
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesSQLiRuleSetMetric

        # AWS Managed Rule - Linux Operating System
        - Name: AWSManagedRulesLinuxRuleSet
          Priority: 4
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
              ExcludedRules: []
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesLinuxRuleSetMetric

        # Rate limiting rule - Prevent brute force attacks
        - Name: RateLimitRule
          Priority: 5
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRuleMetric

        # Block common bot user agents (allow legitimate bots like Googlebot)
        - Name: BlockMaliciousBots
          Priority: 6
          Statement:
            AndStatement:
              Statements:
                - ByteMatchStatement:
                    SearchString: bot
                    FieldToMatch:
                      SingleHeader:
                        Name: user-agent
                    TextTransformations:
                      - Priority: 0
                        Type: LOWERCASE
                    PositionalConstraint: CONTAINS
                - NotStatement:
                    Statement:
                      OrStatement:
                        Statements:
                          - ByteMatchStatement:
                              SearchString: googlebot
                              FieldToMatch:
                                SingleHeader:
                                  Name: user-agent
                              TextTransformations:
                                - Priority: 0
                                  Type: LOWERCASE
                              PositionalConstraint: CONTAINS
                          - ByteMatchStatement:
                              SearchString: bingbot
                              FieldToMatch:
                                SingleHeader:
                                  Name: user-agent
                              TextTransformations:
                                - Priority: 0
                                  Type: LOWERCASE
                              PositionalConstraint: CONTAINS
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: BlockMaliciousBotsMetric

      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub ${EnvironmentName}-waf-metric
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-WAF-CloudFront
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  WAFWebACLId:
    Description: WAF WebACL ID
    Value: !Ref WAFWebACL
    Export:
      Name: !Sub ${AWS::StackName}-WAFWebACLId

  WAFWebACLArn:
    Description: WAF WebACL ARN (use this for CloudFront association)
    Value: !GetAtt WAFWebACL.Arn
    Export:
      Name: !Sub ${AWS::StackName}-WAFWebACLArn
